name: Build test apk after sync

on:
  workflow_run:
    workflows: [Sync Fork]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install the required node packages
        run: npm ci
      
      - name: Generate static web app
        run: npm run generate
      
      - name: Copy web app into native android/ios folders
        run: npx cap sync

      - name: Make ./gradlew command executable
        working-directory: android/
        run: chmod +x ./gradlew
      
      - name: Generate Release APK
        working-directory: android/
        run: ./gradlew assembleRelease
      
      - name: Generate Debug APK
        working-directory: android/
        run: ./gradlew assembleDebug
      
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app_release
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Sign Debug APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app_debug
        with:
          releaseDirectory: android/app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Set tag
        id: tag
        run: echo "tag=$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Rename Release APK
        working-directory: android/app/build/outputs/apk/release/
        run: mv app-release-unsigned-signed.apk testing-release-${{ steps.tag.outputs.tag }}.apk

      - name: Rename Debug APK
        working-directory: android/app/build/outputs/apk/debug/
        run: mv app-debug-signed.apk testing-debug-${{ steps.tag.outputs.tag }}.apk

      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: audiobookshelf-apk
          path: |
            android/app/build/outputs/apk/release/testing-release-${{ steps.tag.outputs.tag }}.apk
            android/app/build/outputs/apk/debug/testing-debug-${{ steps.tag.outputs.tag }}.apk
       
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.tag.outputs.tag }}
          prerelease: true
          title: "Testing Build"
          files: |
            android/app/build/outputs/apk/release/testing-release-${{ steps.tag.outputs.tag }}.apk
            android/app/build/outputs/apk/debug/testing-debug-${{ steps.tag.outputs.tag }}.apk