name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: advplyr
          base: testing
          head: master
          merge_method: merge